version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 0

- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "v2.x"
  schedule:
    interval: "weekly"
  labels:
  - "v2.x"
  - "github_actions"
  - "dependencies"
  open-pull-requests-limit: 0

- package-ecosystem: "gomod"
  directory: "/src"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 0

- package-ecosystem: "gomod"
  directory: "/src"
  target-branch: "v2.x"
  schedule:
    interval: "weekly"
  labels:
  - "v2.x"
  - "go"
  - "dependencies"
  open-pull-requests-limit: 0

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 0
