version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 100

- package-ecosystem: "gomod"
  directory: "/src"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 100

- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 100
