#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/log-cache
LOG_DIR=/var/vcap/sys/log/log-cache
PIDFILE=${RUN_DIR}/log-cache.pid
JOB_DIR=/var/vcap/jobs/log-cache
CERT_DIR=$JOB_DIR/config/certs

PACKAGE_DIR=/var/vcap/packages/log-cache
ENVIRONMENT=/var/vcap/jobs/log-cache/bin/environment.sh

case $1 in

  start)
    set +e
      killall -15 log-cache
      killall -9 log-cache
      killall -2 log-cache
      killall -3 log-cache
    set -e

    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    cd $PACKAGE_DIR

    ulimit -n 8192

    source $ENVIRONMENT
    echo $$ > $PIDFILE
    exec chpst -u vcap:vcap ./log-cache &>> ${LOG_DIR}/log-cache.log

    ;;

  stop)
    set +e
      killall -15 log-cache
      killall -9 log-cache
      killall -2 log-cache
      killall -3 log-cache
    set -e

    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
