#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/metric-cache
LOG_DIR=/var/vcap/sys/log/metric-cache
PIDFILE=${RUN_DIR}/metric-cache.pid
JOB_DIR=/var/vcap/jobs/metric-cache
CERT_DIR=$JOB_DIR/config/certs

PACKAGE_DIR=/var/vcap/packages/metric-cache
ENVIRONMENT=/var/vcap/jobs/metric-cache/bin/environment.sh

case $1 in

  start)
    set +e
      killall -15 metric-cache
      killall -9 metric-cache
      killall -2 metric-cache
      killall -3 metric-cache
    set -e

    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    cd $PACKAGE_DIR

    ulimit -n 8192

    source $ENVIRONMENT
    echo $$ > $PIDFILE
    exec chpst -u vcap:vcap ./metric-cache &>> ${LOG_DIR}/metric-cache.log

    ;;

  stop)
    set +e
      killall -15 metric-cache
      killall -9 metric-cache
      killall -2 metric-cache
      killall -3 metric-cache
    set -e

    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
