#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/log-cache-expvar-forwarder
LOG_DIR=/var/vcap/sys/log/log-cache-expvar-forwarder
PIDFILE=${RUN_DIR}/log-cache-expvar-forwarder.pid
JOB_DIR=/var/vcap/jobs/log-cache-expvar-forwarder
CERT_DIR=$JOB_DIR/config/certs

PACKAGE_DIR=/var/vcap/packages/log-cache-expvar-forwarder
ENVIRONMENT=/var/vcap/jobs/log-cache-expvar-forwarder/bin/environment.sh

case $1 in

  start)
    set +e
      killall -15 log-cache-expvar-forwarder
      killall -9 log-cache-expvar-forwarder
      killall -2 log-cache-expvar-forwarder
      killall -3 log-cache-expvar-forwarder
    set -e

    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    cd $PACKAGE_DIR

    ulimit -n 8192

    source $ENVIRONMENT
    echo $$ > $PIDFILE

    exec >>${LOG_DIR}/captured-metrics.log \
        2>>${LOG_DIR}/log-cache-expvar-forwarder.log

    exec chpst -u vcap:vcap ./log-cache-expvar-forwarder

    ;;

  stop)
    set +e
      killall -15 log-cache-expvar-forwarder
      killall -9 log-cache-expvar-forwarder
      killall -2 log-cache-expvar-forwarder
      killall -3 log-cache-expvar-forwarder
    set -e

    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
