#!/bin/bash

set -eux
set -o pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if ! command -v bundle &> /dev/null; then
  gem install bundler
fi

pushd "${SCRIPT_DIR}/../.." > /dev/null
    bundle install
    bundle exec rspec
popd > /dev/null

