#!/bin/bash -e

RUN_DIR=/var/vcap/sys/run/metric-cache-cf-auth-proxy
LOG_DIR=/var/vcap/sys/log/metric-cache-cf-auth-proxy
PIDFILE=${RUN_DIR}/metric-cache-cf-auth-proxy.pid
JOB_DIR=/var/vcap/jobs/metric-cache-cf-auth-proxy
CERT_DIR=$JOB_DIR/config/certs

PACKAGE_DIR=/var/vcap/packages/log-cache-cf-auth-proxy
ENVIRONMENT=/var/vcap/jobs/metric-cache-cf-auth-proxy/bin/environment.sh

case $1 in

  start)
    set +e
      killall -15 log-cache-cf-auth-proxy
      killall -9 log-cache-cf-auth-proxy
      killall -2 log-cache-cf-auth-proxy
      killall -3 log-cache-cf-auth-proxy
    set -e

    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    cd $PACKAGE_DIR

    ulimit -n 8192

    source $ENVIRONMENT
    echo $$ > $PIDFILE
    exec chpst -u vcap:vcap ./log-cache-cf-auth-proxy &>> ${LOG_DIR}/metric-cache-cf-auth-proxy.log

    ;;

  stop)
    set +e
      killall -15 log-cache-cf-auth-proxy
      killall -9 log-cache-cf-auth-proxy
      killall -2 log-cache-cf-auth-proxy
      killall -3 log-cache-cf-auth-proxy
    set -e

    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
