#!/bin/bash

bosh -e lite -d log-cache deploy manifests/log-cache.yml \
    --vars-store deployment-vars.yml \
    --vars-file /tmp/loggregator-vars.yml \
    --var system_domain=bosh-lite.com \
    --var datadog_api_key="$DATADOG_API_KEY" \
    --no-redact
