#!/bin/bash
set -e

go get github.com/vito/gosub

if [ ! $(which gosub) ]; then
    echo "Gosub required to update dependencies in bosh/*/spec files."
    echo 'Please install with `go get github.com/vito/gosub`'
    exit 1
fi

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'
      gosub list "$@" | \
        sed -e 's|\(.*\)|- \1/*.go # gosub|g'
    } > spec.new

    mv spec.new spec

  )
}

sync_package log-cache                   -app  code.cloudfoundry.org/log-cache/cmd/logcache &
sync_package log-cache-gateway           -app  code.cloudfoundry.org/log-cache/cmd/gateway &
sync_package log-cache-nozzle            -app  code.cloudfoundry.org/log-cache/cmd/nozzle &
sync_package log-cache-expvar-forwarder  -app  code.cloudfoundry.org/log-cache/cmd/expvar-forwarder &
sync_package log-cache-group-reader      -app  code.cloudfoundry.org/log-cache/cmd/group-reader &

wait
